/*
 * This file is generated by jOOQ.
 */
package io.uetunited.oneheed.entity.public_.tables.records;


import io.uetunited.oneheed.entity.public_.tables.Conversations;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConversationsRecord extends TableRecordImpl<ConversationsRecord> implements Record8<String, String, String, String, Timestamp, Timestamp, String, String> {

    private static final long serialVersionUID = 1414248090;

    /**
     * Setter for <code>public.conversations.page_id</code>.
     */
    public void setPageId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.conversations.page_id</code>.
     */
    public String getPageId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.conversations.customer_id</code>.
     */
    public void setCustomerId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.conversations.customer_id</code>.
     */
    public String getCustomerId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.conversations.user_id</code>.
     */
    public void setUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.conversations.user_id</code>.
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.conversations.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.conversations.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.conversations.start_at</code>.
     */
    public void setStartAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.conversations.start_at</code>.
     */
    public Timestamp getStartAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.conversations.end_at</code>.
     */
    public void setEndAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.conversations.end_at</code>.
     */
    public Timestamp getEndAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.conversations.channel</code>.
     */
    public void setChannel(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.conversations.channel</code>.
     */
    public String getChannel() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.conversations.id</code>.
     */
    public void setId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.conversations.id</code>.
     */
    public String getId() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, Timestamp, Timestamp, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, Timestamp, Timestamp, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Conversations.CONVERSATIONS.PAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Conversations.CONVERSATIONS.CUSTOMER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Conversations.CONVERSATIONS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Conversations.CONVERSATIONS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Conversations.CONVERSATIONS.START_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Conversations.CONVERSATIONS.END_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Conversations.CONVERSATIONS.CHANNEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Conversations.CONVERSATIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getPageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getStartAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getEndAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getChannel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getStartAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getEndAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getChannel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConversationsRecord value1(String value) {
        setPageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConversationsRecord value2(String value) {
        setCustomerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConversationsRecord value3(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConversationsRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConversationsRecord value5(Timestamp value) {
        setStartAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConversationsRecord value6(Timestamp value) {
        setEndAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConversationsRecord value7(String value) {
        setChannel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConversationsRecord value8(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConversationsRecord values(String value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConversationsRecord
     */
    public ConversationsRecord() {
        super(Conversations.CONVERSATIONS);
    }

    /**
     * Create a detached, initialised ConversationsRecord
     */
    public ConversationsRecord(String pageId, String customerId, String userId, String status, Timestamp startAt, Timestamp endAt, String channel, String id) {
        super(Conversations.CONVERSATIONS);

        set(0, pageId);
        set(1, customerId);
        set(2, userId);
        set(3, status);
        set(4, startAt);
        set(5, endAt);
        set(6, channel);
        set(7, id);
    }
}
