/*
 * This file is generated by jOOQ.
 */
package io.uetunited.oneheed.entity.public_.tables.records;


import io.uetunited.oneheed.entity.public_.tables.TagConversations;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagConversationsRecord extends TableRecordImpl<TagConversationsRecord> implements Record6<String, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = -173527650;

    /**
     * Setter for <code>public.tag_conversations.tag_id</code>.
     */
    public void setTagId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tag_conversations.tag_id</code>.
     */
    public String getTagId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.tag_conversations.customer_id</code>.
     */
    public void setCustomerId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tag_conversations.customer_id</code>.
     */
    public String getCustomerId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tag_conversations.conversation_id</code>.
     */
    public void setConversationId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tag_conversations.conversation_id</code>.
     */
    public String getConversationId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tag_conversations.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tag_conversations.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tag_conversations.created_at</code>.
     */
    public void setCreatedAt(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tag_conversations.created_at</code>.
     */
    public String getCreatedAt() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tag_conversations.expire</code>.
     */
    public void setExpire(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tag_conversations.expire</code>.
     */
    public Timestamp getExpire() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TagConversations.TAG_CONVERSATIONS.TAG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TagConversations.TAG_CONVERSATIONS.CUSTOMER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TagConversations.TAG_CONVERSATIONS.CONVERSATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TagConversations.TAG_CONVERSATIONS.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TagConversations.TAG_CONVERSATIONS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TagConversations.TAG_CONVERSATIONS.EXPIRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getConversationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getExpire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getConversationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getExpire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagConversationsRecord value1(String value) {
        setTagId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagConversationsRecord value2(String value) {
        setCustomerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagConversationsRecord value3(String value) {
        setConversationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagConversationsRecord value4(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagConversationsRecord value5(String value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagConversationsRecord value6(Timestamp value) {
        setExpire(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagConversationsRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagConversationsRecord
     */
    public TagConversationsRecord() {
        super(TagConversations.TAG_CONVERSATIONS);
    }

    /**
     * Create a detached, initialised TagConversationsRecord
     */
    public TagConversationsRecord(String tagId, String customerId, String conversationId, String createdBy, String createdAt, Timestamp expire) {
        super(TagConversations.TAG_CONVERSATIONS);

        set(0, tagId);
        set(1, customerId);
        set(2, conversationId);
        set(3, createdBy);
        set(4, createdAt);
        set(5, expire);
    }
}
