language: java
sudo: false
env:
- CODECOV_TOKEN="b84087bc-4a81-4799-8257-f4858cf68aff"
branches:
  only:
  - master
  - develop
addons:
  ssh_known_hosts: 173.212.251.237
before_install:
- openssl aes-256-cbc -K $encrypted_9ae803e79d3a_key -iv $encrypted_9ae803e79d3a_iv
  -in deploy_key.enc -out ./deploy_key -d
script: mvn cobertura:cobertura
after_success:
- bash <(curl -s https://codecov.io/bash)
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host 173.212.251.237\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@173.212.251.237 pwd
- scp -i ./deploy_key -v target/vcare-0.0.1-SNAPSHOT.jar root@173.212.251.237:/opt/vcare/vcare-backend
git:
  depth: 1
