/*
 * This file is generated by jOOQ.
 */
package io.uetunited.oneheed.entity.public_;


import io.uetunited.oneheed.entity.public_.tables.Roles;
import io.uetunited.oneheed.entity.public_.tables.UserRoles;
import io.uetunited.oneheed.entity.public_.tables.Users;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ROLES_PKEY = Indexes0.ROLES_PKEY;
    public static final Index UK_NB4H0P6TXRMFC0XBRD1KGLP9T = Indexes0.UK_NB4H0P6TXRMFC0XBRD1KGLP9T;
    public static final Index USER_ROLES_PKEY = Indexes0.USER_ROLES_PKEY;
    public static final Index UK6DOTKOTT2KJSP8VW4D0M25FB7 = Indexes0.UK6DOTKOTT2KJSP8VW4D0M25FB7;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ROLES_PKEY = Internal.createIndex("roles_pkey", Roles.ROLES, new OrderField[] { Roles.ROLES.ID }, true);
        public static Index UK_NB4H0P6TXRMFC0XBRD1KGLP9T = Internal.createIndex("uk_nb4h0p6txrmfc0xbrd1kglp9t", Roles.ROLES, new OrderField[] { Roles.ROLES.NAME }, true);
        public static Index USER_ROLES_PKEY = Internal.createIndex("user_roles_pkey", UserRoles.USER_ROLES, new OrderField[] { UserRoles.USER_ROLES.USER_ID, UserRoles.USER_ROLES.ROLE_ID }, true);
        public static Index UK6DOTKOTT2KJSP8VW4D0M25FB7 = Internal.createIndex("uk6dotkott2kjsp8vw4d0m25fb7", Users.USERS, new OrderField[] { Users.USERS.EMAIL }, true);
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
    }
}
