/*
 * This file is generated by jOOQ.
 */
package io.uetunited.oneheed.entity.public_;


import io.uetunited.oneheed.entity.public_.tables.Roles;
import io.uetunited.oneheed.entity.public_.tables.UserRoles;
import io.uetunited.oneheed.entity.public_.tables.Users;
import io.uetunited.oneheed.entity.public_.tables.records.RolesRecord;
import io.uetunited.oneheed.entity.public_.tables.records.UserRolesRecord;
import io.uetunited.oneheed.entity.public_.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RolesRecord, Long> IDENTITY_ROLES = Identities0.IDENTITY_ROLES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RolesRecord> ROLES_PKEY = UniqueKeys0.ROLES_PKEY;
    public static final UniqueKey<RolesRecord> UK_NB4H0P6TXRMFC0XBRD1KGLP9T = UniqueKeys0.UK_NB4H0P6TXRMFC0XBRD1KGLP9T;
    public static final UniqueKey<UserRolesRecord> USER_ROLES_PKEY = UniqueKeys0.USER_ROLES_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;
    public static final UniqueKey<UsersRecord> UK6DOTKOTT2KJSP8VW4D0M25FB7 = UniqueKeys0.UK6DOTKOTT2KJSP8VW4D0M25FB7;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserRolesRecord, UsersRecord> USER_ROLES__USER_ROLES_FK_1 = ForeignKeys0.USER_ROLES__USER_ROLES_FK_1;
    public static final ForeignKey<UserRolesRecord, RolesRecord> USER_ROLES__USER_ROLES_FK = ForeignKeys0.USER_ROLES__USER_ROLES_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<RolesRecord, Long> IDENTITY_ROLES = Internal.createIdentity(Roles.ROLES, Roles.ROLES.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<RolesRecord> ROLES_PKEY = Internal.createUniqueKey(Roles.ROLES, "roles_pkey", Roles.ROLES.ID);
        public static final UniqueKey<RolesRecord> UK_NB4H0P6TXRMFC0XBRD1KGLP9T = Internal.createUniqueKey(Roles.ROLES, "uk_nb4h0p6txrmfc0xbrd1kglp9t", Roles.ROLES.NAME);
        public static final UniqueKey<UserRolesRecord> USER_ROLES_PKEY = Internal.createUniqueKey(UserRoles.USER_ROLES, "user_roles_pkey", UserRoles.USER_ROLES.USER_ID, UserRoles.USER_ROLES.ROLE_ID);
        public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, "users_pkey", Users.USERS.ID);
        public static final UniqueKey<UsersRecord> UK6DOTKOTT2KJSP8VW4D0M25FB7 = Internal.createUniqueKey(Users.USERS, "uk6dotkott2kjsp8vw4d0m25fb7", Users.USERS.EMAIL);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<UserRolesRecord, UsersRecord> USER_ROLES__USER_ROLES_FK_1 = Internal.createForeignKey(io.uetunited.oneheed.entity.public_.Keys.USERS_PKEY, UserRoles.USER_ROLES, "user_roles__user_roles_fk_1", UserRoles.USER_ROLES.USER_ID);
        public static final ForeignKey<UserRolesRecord, RolesRecord> USER_ROLES__USER_ROLES_FK = Internal.createForeignKey(io.uetunited.oneheed.entity.public_.Keys.ROLES_PKEY, UserRoles.USER_ROLES, "user_roles__user_roles_fk", UserRoles.USER_ROLES.ROLE_ID);
    }
}
