/*
 * This file is generated by jOOQ.
 */
package io.uetunited.oneheed.entity.public_.tables;


import io.uetunited.oneheed.entity.public_.Public;
import io.uetunited.oneheed.entity.public_.tables.records.TagConversationsRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagConversations extends TableImpl<TagConversationsRecord> {

    private static final long serialVersionUID = -1559616494;

    /**
     * The reference instance of <code>public.tag_conversations</code>
     */
    public static final TagConversations TAG_CONVERSATIONS = new TagConversations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TagConversationsRecord> getRecordType() {
        return TagConversationsRecord.class;
    }

    /**
     * The column <code>public.tag_conversations.tag_id</code>.
     */
    public final TableField<TagConversationsRecord, String> TAG_ID = createField("tag_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.tag_conversations.customer_id</code>.
     */
    public final TableField<TagConversationsRecord, String> CUSTOMER_ID = createField("customer_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.tag_conversations.conversation_id</code>.
     */
    public final TableField<TagConversationsRecord, String> CONVERSATION_ID = createField("conversation_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.tag_conversations.created_by</code>.
     */
    public final TableField<TagConversationsRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.tag_conversations.created_at</code>.
     */
    public final TableField<TagConversationsRecord, String> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.tag_conversations.expire</code>.
     */
    public final TableField<TagConversationsRecord, Timestamp> EXPIRE = createField("expire", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>public.tag_conversations</code> table reference
     */
    public TagConversations() {
        this(DSL.name("tag_conversations"), null);
    }

    /**
     * Create an aliased <code>public.tag_conversations</code> table reference
     */
    public TagConversations(String alias) {
        this(DSL.name(alias), TAG_CONVERSATIONS);
    }

    /**
     * Create an aliased <code>public.tag_conversations</code> table reference
     */
    public TagConversations(Name alias) {
        this(alias, TAG_CONVERSATIONS);
    }

    private TagConversations(Name alias, Table<TagConversationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private TagConversations(Name alias, Table<TagConversationsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TagConversations(Table<O> child, ForeignKey<O, TagConversationsRecord> key) {
        super(child, key, TAG_CONVERSATIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagConversations as(String alias) {
        return new TagConversations(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagConversations as(Name alias) {
        return new TagConversations(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TagConversations rename(String name) {
        return new TagConversations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TagConversations rename(Name name) {
        return new TagConversations(name, null);
    }
}
